services:
  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        GID: '${GID}'
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      UID: '${UID}'

  mysql:
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

