services:
  nginx:
    image: nginx:latest
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        GID: '${GID}'
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini

      - .:/var/www/html
    ports:
      - ":9000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      UID: '${UID}'

  mysql:
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
    networks:
      - app-network
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025 # web ui
      - 1025:1025 # smtp
    volumes:
      - ./.docker/mailpit/db:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

